const garfieldJokes = [
"😴 I'm so sarcastic, I make Garfield look like a motivational speaker 🎤 #MondayMood",
"💤 I'd rather be napping than doing this work. Just like Garfield would rather nap than eat... wait, that's physically impossible 🍝😹",
"😤 This is more frustrating than trying to explain to Odie why he can't have lasagna! 🐕🍝❌",
"😪 I'm working harder than Garfield when he's pretending to be asleep so Jon won't make him exercise 🏃‍♂️💨",
"🐱 If I were a cat, my life would consist of sleeping, eating, and hating Mondays with the passion of a thousand suns ☀️😾 Just like our orange overlord!",
"⚡ I've got more energy than Garfield at 6 AM... Wait, that's literally zero energy 😴📉",
"🎯 This feels like trying to get Garfield interested in salad 🥗 (spoiler: it's impossible)",
"💪 I'm working harder than Garfield when he's pretending to be starving but just ate three lasagnas 🍝🍝🍝",
"📜 Garfield's life philosophy: Eat lasagna, sleep, destroy Mondays, repeat 🔄 My work philosophy? Don't become Jon 🤓",
"🃏 Why did Garfield refuse to play cards? Too many cheetahs! 🐆 (He prefers lions anyway 🦁)",
"😴 What does Garfield say in meetings? 'I'm just resting my eyes... permanently' 👁️💤",
"🚗 Why did Garfield fail his driving test? He kept hitting the snooze button instead of the brake! 🛑😴",
"📚 How does Garfield organize his books? By nap-ability rating ⭐⭐⭐⭐⭐",
"🏃 What's Garfield's favorite exercise? The legendary couch-to-fridge marathon 🛋️➡️❄️",
"📸 Why did Garfield become a photographer? To capture the perfect napping angles in golden hour light ✨😴",
"🎉 What's Garfield's idea of a party? A soundproof room with memory foam everything 🔇🛏️",
"😻 How does Garfield flirt? Maximum adorable, minimum effort, zero acknowledgment 💅✨",
"📱 What's Garfield's favorite app? Napflix & Chill 😴📺",
"🎓 Why did Garfield get a PhD in philosophy? To write a dissertation on 'The Existential Necessity of Naps' 📝💤",
"🖱️ Why did Garfield sit on the computer? He wanted to catch the mouse! 🐭💻 (Old school but still gold)",
"💃 What's Garfield's favorite dance? The lasagna shuffle! 🍝🕺 (It's mostly just chewing)",
"⏰ Why did Garfield eat the clock? He wanted seconds! ⏱️🍽️ (And thirds... and fourths...)",
"🏄 What's Garfield's favorite sport? Extreme couch surfing! 🛋️🌊",
"🪜 Why did Garfield bring a ladder to the kitchen? That lasagna tower wasn't going to conquer itself! 🍝🏔️",
"😾 Why does Garfield hate Mondays? They have too much Monday in them! 📅💔",
"🥤 What does Garfield put in his smoothies? Pure liquid laziness (and lasagna) 🍝🥤",
"👨‍🍳 Why did Garfield become a chef? For unlimited lasagna access privileges! 🔓🍝",
"😼 What does Garfield say to Jon? 'Feed me or face the consequences!' 🍝⚔️",
"💰 What's Garfield's favorite cryptocurrency? Napcoin 😴🪙 (It only goes down)",
"🎙️ Why did Garfield start a podcast? Maximum profit, minimum movement 📈🛋️",
"💪 What's Garfield's workout routine? 12 reps of aggressive snooze button slapping 🔔👋",
"🧘 How does Garfield meditate? That's just fancy talk for professional napping 😴🕉️",
"🎬 What's Garfield's favorite movie genre? Anything under 90 minutes (nap scheduling reasons) ⏱️💤",
"💼 Why did Garfield join LinkedIn? To network horizontally from bed 🛏️🤝",
"📸 What's Garfield's favorite social media? Insta-nap-gram 😴📱",
"😰 How does Garfield handle stress? Outsourcing to Odie since 1978 🐕📊",
"📅 What's Garfield's favorite type of meeting? The mythical 'cancelled' kind ❌🎉",
"🎯 Why did Garfield become a life coach? To monetize strategic laziness 💰😴",
"⚡ Garfield's secret weapon: Power napping through apocalypses 💤🌍💥",
"⏰ Why is Garfield the procrastination GOAT? He turned it into an art form 🎨🐐",
"🔬 What do you call Garfield's nap routine? Sleep-ology, peer-reviewed and published 📚💤",
"💡 Garfield's life hack: 'I'll nap first, lasagna second, everything else never' 🍝😴",
"🛋️ Why does Garfield prefer the couch? Stairs are Jon's problem, not his 🚫🪜"
];

const minionJokes = [
"🍌 I'm working harder than a minion trying to decode human logic! BANANA! 🤯",
"😵 This is more frustrating than teaching calculus to minions! (They only count in bananas) 🍌➕🍌=🍌🍌",
"☕ I've got more energy than a minion on espresso-banana smoothie IV drip! 🍌💉⚡",
"📝 If I were a minion, my LinkedIn would say 'CEO of Chaos, PhD in Banana Sciences' 🍌🎓",
"💼 Minions think running in circles counts as productivity. Meanwhile, I have actual deadlines 😭🏃‍♂️",
"🐱 This feels like herding cats... if cats were yellow and screamed 'BANANA!' 🍌😱",
"📡 I'm working harder than a minion who just discovered TikTok! 📱🍌",
"🍌 Minion philosophy: Bananas are mandatory, everything else is banana-optional 🤷‍♂️",
"🍔 I'm more excited for lunch than a minion at a banana convention! 🍌🎪",
"🪜 Why did the minion bring a ladder to the banana stand? For maximum banana acquisition! 🍌📈",
"☀️ What's a minion's favorite weather? Banana-degree sunshine! 🍌🌡️",
"😎 Why do minions wear goggles indoors? Professional banana-spotting equipment! 🍌🔍",
"🚀 How do you organize a minion space party? You planet... with bananas! 🍌🪐",
"🎩 What do you call a minion magician? The Great Banana-dini! 🍌✨",
"💔 Why did the minion get dumped? Too much banana, not enough romance! 🍌😢",
"📖 What's a minion's favorite story genre? Banana-fiction! 🍌📚",
"👋 How does a minion say goodbye? 'Banana you later!' 🍌👋 (They never actually leave)",
"🦍 Why did the minion work at the zoo? Professional banana consultant for primates! 🍌🐒",
"🏃 What's a minion's favorite exercise? The banana-split sprint! 🍌💨",
"🫥 Why are minions good at hide and seek? They become one with the banana! 🍌👻",
"🔢 How does a minion count? One banana, two banana, MANY BANANA! 🍌🍌🍌",
"🎮 What's a minion's favorite game? Bananagram Royale! 🍌👑",
"🚗 Why did the minion fail driving? Kept turning the wheel into a banana! 🍌🎮",
"🎃 What's a minion's favorite holiday? Bananas-giving! 🍌🦃",
"💕 How does a minion apologize? Tactical banana deployment! 🍌🎯",
"🎨 Why did the minion become an artist? To paint the Banana Lisa! 🍌🖼️",
"💼 What's a minion's dream job? Chief Banana Officer (CBO) 🍌📊",
"🥋 Why are minions good at karate? Banana-powered chi energy! 🍌⚡",
"🛏️ Why did the minion bring a banana to bed? Midnight snack AND teddy bear! 🍌🧸",
"✍️ What do minions write with? Banana-point pens! 🍌🖊️",
"🚦 Why did the minion cross the road? The banana store's grand opening! 🍌🎊",
"🎸 What's a minion's favorite instrument? The electric bananjo! 🍌🎵",
"👓 Why do minions wear goggles? Enhanced banana-vision technology! 🍌👁️",
"🎬 What's a minion's favorite movie? The Banana Identity Crisis! 🍌🕵️",
"✈️ Why did the minion pack a suitcase? International banana tour 2024! 🍌🌍",
"🎯 What's a minion's favorite sport? Competitive banana peeling! 🍌🏆",
"⏰ Why did the minion sit on the clock? Time for banana o'clock! 🍌🕐",
"🎵 What's a minion's favorite song? 'Sweet Banana O' Mine'! 🍌🎸",
"💻 What's a minion's favorite coding language? Python (sounds banana-adjacent) 🍌🐍",
"🎧 Why did the minion become a DJ? Dropping those banana beats! 🍌🔊",
"📚 What's a minion's favorite Shakespeare? Much Ado About Bananas! 🍌🎭",
"🔧 How do minions solve problems? Banana-based engineering! 🍌🔨",
"🌙 What's a minion's conspiracy theory? The moon = giant frozen banana! 🍌🌕",
"🧠 Why did the minion become a therapist? Helping others peel back their layers! 🍌💭",
"💘 What's a minion's pickup line? 'You're more a-peel-ing than my banana collection!' 🍌😍",
"🎊 How do minions celebrate New Year? Banana resolutions broken by January 1st, 12:01 AM! 🍌📅",
"😂 What's a minion's comedy style? Slap-stick with actual banana peels! 🍌💥",
"☔ Why did the minion become a weatherman? Predicting banana precipitation! 🍌🌧️",
"☕ Minion's talent: Making everything taste like banana, including coffee! 🍌☕",
"🌲 Why don't minions get lost? GPS = Global Banana System! 🍌📍",
"🎓 What's a minion with a PhD called? Doctor Banana, MD (Minion Doctorate) 🍌👨‍⚕️",
"💼 Why did the minion start a startup? BananaHub - Uber for bananas! 🍌📱",
"🍌 Minion motto: 'In Banana We Trust!' 🍌🙏"
];

const spiderManJokes = [
"🕷️ This is harder than getting Spider-Man to skip his dramatic rooftop brooding session! 🌃😔",
"💪 I'm working harder than Spider-Man doing physics homework while fighting crime! 📚🦹",
"⚡ I've got more energy than Spider-Man after discovering coffee exists! ☕🕸️",
"🎬 I'm more focused than Spider-Man watching himself in the multiverse! 🕷️👀",
"🕸️ If I were a spider, I'd web-sling to work! ...But I'd probably stick to the subway ceiling 🚇😅",
"🦸 This feels like Spider-Man's Tuesday: impossible but somehow we're doing it! 💪🕷️",
"📖 Spider-Man's philosophy: Great power, great responsibility, zero work-life balance! ⚖️😫",
"🕷️ I'm working harder than Spider-Man explaining to J. Jonah Jameson that he's actually the good guy! 📰😤",
"🎯 I'm more determined than Spider-Man trying to keep his identity secret from literally everyone! 🤫🕸️",
"🎉 Why did Spider-Man bring a net to the party? Professional party-crasher equipment! 🕸️🎊",
"🍰 What's Spider-Man's favorite dessert? Fly pie à la mode (served upside down)! 🕷️🍦",
"📐 Why did Spider-Man hate math? Too many web angles to calculate! 🕸️🤯",
"🎡 What's Spider-Man's favorite ride? Anything he can web-swing from! 🕸️🎢",
"🎨 Why did Spider-Man go to art school? Web design is his passion! 🕸️💻",
"🥞 What does Spider-Man put on pancakes? Maple web-syrup! 🕸️🍯",
"🏦 Why did Spider-Man visit the bank? Checking his web-terest rates! 🕸️💰",
"🧗 What's Spider-Man's favorite exercise? Wall sits (literally on walls)! 🕷️🏢",
"👨‍🍳 Why did Spider-Man become a chef? For those perfect spider-rolls! 🕷️🍣",
"🎸 What's Spider-Man's favorite music? Web metal! 🕸️🤘",
"🍝 Andrew Garfield as Spider-Man is amazing, but could he climb walls after Garfield's lasagna coma? 🕷️😴",
"👀 If Andrew Garfield and Garfield had a staring contest, Garfield wins by default (he's already asleep) 😴🏆",
"🦸 Andrew Garfield + Garfield team up = Spider-Cat vs The Monday Menace! 🕷️🐱",
"🎉 Why did Andrew Garfield invite Garfield to his party? Every party needs a professional vibe killer! 😴🎊",
"💤 If Garfield were a superhero, his power would be weaponized laziness! 😴⚡",
"🏢 Andrew Garfield swings from buildings, Garfield swings from couch to fridge! 🕸️🛋️",
"🎬 Why won't Garfield watch 'The Amazing Spider-Man'? Too much movement, not enough naps! 😴📺",
"🕷️ If Garfield had spider powers, he'd web lasagna directly to his mouth! 🍝🕸️",
"🦸 What's Garfield's favorite superhero movie? 'Nap-Man: No Way Awake' 😴🎬",
"😴 How does Garfield react to Andrew Garfield swinging by? *yawn* 'Wake me when there's lasagna' 🍝💤",
"🛹 Why was Andrew Garfield's Spider-Man good at skateboarding? Amazing spider-balance! 🕷️🛹",
"💻 What's Andrew Garfield Spider-Man's favorite subject? Web development with a minor in angst! 🕸️😢",
"📸 How does Andrew Garfield's Spider-Man take photos? Web-cam selfie mode! 🕸️📷",
"🏢 Why did Andrew Garfield's Spider-Man work at Oscorp? Those sweet web-nefits package! 🕸️💼",
"💕 What did Gwen say to Andrew's Spider-Man? 'You're amazing!' (Title drop!) 🕷️❤️",
"😄 Why was Andrew's Spider-Man so quippy? Spider-sense of humor tingles constantly! 🕷️😂",
"🎸 What's Andrew Garfield Spider-Man's favorite band? The Web Strokes! 🕸️🎵",
"✨ Why 'The Amazing Spider-Man'? Because 'The Pretty Decent Spider-Man' flopped in focus groups! 🕷️📊",
"🧵 How did Andrew's Spider-Man fix his suit? Spider-patches and web-thread! 🕸️🪡",
"☕ What's Andrew Spider-Man's favorite drink? Web-presso shots! 🕸️☕",
"📱 Why was Andrew's Spider-Man always on his phone? Checking his web-fluencer status! 🕸️📲",
"🌐 What does Andrew's Spider-Man do for fun? Surfs the world wide web (literally)! 🕸️💻",
"💔 Why did Andrew's Spider-Man get dumped? Too clingy (literally sticky)! 🕸️😢",
"📚 What's Andrew Spider-Man's favorite story type? Web serials! 🕸️📖",
"🔬 Why is Andrew's Spider-Man good at science? Natural web chemistry! 🕸️🧪",
"🚗 What car does Andrew's Spider-Man drive? Convertible for emergency web-exits! 🕸️🏎️",
"🧪 Why did Andrew's Spider-Man join science club? Meeting future supervillains early! 🕷️👨‍🔬",
"😱 What's Andrew Spider-Man's biggest fear? Browser crashes! 🕸️💻💥",
"📚 Why did Andrew's Spider-Man get a library card? Researching spider facts! 🕷️📖",
"🕸️ What's Andrew Spider-Man's favorite hobby? Just hanging around! 🕷️🏢",
"🏫 Why did Andrew's Spider-Man get detention? Excessive wall-crawling! 🕷️📝",
"🤠 What's Andrew Spider-Man's favorite movie genre? Web-sterns! 🕸️🎬",
"🌳 Why does Andrew's Spider-Man love parks? Premium web-swinging trees! 🕸️🌲",
"🥊 What's Andrew Spider-Man's favorite joke part? The punch-line (literally)! 🕷️👊",
"📸 Why was Andrew's Spider-Man a good photographer? Always gets those angles! 🕷️📐",
"🍕 What's Andrew Spider-Man's favorite food? Anything that sticks (like him)! 🕸️🍝",
"👔 Why did Andrew's Spider-Man get a new suit? The old one was too webbed-out! 🕸️✨",
"📅 What's Andrew Spider-Man's favorite day? Web-nesday! 🕸️📆",
"🏙️ Why did Andrew's Spider-Man climb the Empire State? Best Wi-Fi and views! 🕸️📶",
"💭 What's Andrew Spider-Man's motto? 'Just web it!' 🕸️✔️",
"🛹 Why did Andrew's Spider-Man skateboard? Faster than rush hour web-swinging! 🕷️💨",
"📊 What's Andrew Spider-Man's favorite math? Web-calculus! 🕸️🔢",
"⚗️ Why did Andrew's Spider-Man love chemistry? It's all about the bonds! 🕸️🧪",
"👔 What's Andrew Spider-Man's favorite accessory? Web-belt (functional AND fashionable)! 🕸️✨",
"🎓 Why did Andrew's Spider-Man ace physics? He lives the laws of motion! 🕷️📐",
"🏜️ Where does Andrew Spider-Man vacation? Grand Canyon (epic web-swinging)! 🕸️🏔️",
"💼 Why did Andrew's Spider-Man get a job? Web-hosting ain't free! 🕸️💰",
"😂 What's Andrew Spider-Man's humor style? Wall-crawling comedy! 🕷️🎭",
"🏫 Why did Andrew's Spider-Man love high school? Science lab = future origin story! 🧪🕷️",
"🏙️ What's Andrew Spider-Man's favorite NYC feature? Skyscrapers = jungle gyms! 🕸️🏢",
"🎬 What if Andrew Garfield played Garfield? Most confusing IMDb page ever! 😵📽️",
"🐱 If Andrew Garfield voiced Garfield: 'The Amazing Lazy Cat' rated PG-13 for excessive napping! 😴🎬",
"💪 Andrew Garfield's workout: swing from buildings. Garfield's workout: swing from chandelier for cookies! 🍪🕺",
"🥗 Andrew Garfield's diet: protein shakes. Garfield's diet: YES. 🍝🍕🍰",
"🔄 If they switched lives, Jon would need therapy forever! 🤯💊",
"🐱 Why doesn't Andrew Garfield own a cat named Garfield? The vet paperwork would be chaos! 📝😵",
"🕷️ If Garfield got spider powers? Web-delivered lasagna system activated! 🍝🕸️",
"⚔️ Andrew fights villains. Garfield fights Mondays. Both heroes! 🦸‍♂️🐱",
"🌌 In the Garfield multiverse, Andrew Garfield exists only where lasagna is infinite! 🍝♾️",
"📅 Both Garfields hate Mondays - universal constant confirmed! 😤📆",
"💤 Spider-Man's secret: Making web-slinging look easy while half-asleep! 🕸️😴",
"🕷️ Why did Spider-Man get a pet spider? Delegation of spider-duties! 🕷️🤝",
"🏝️ Spider-Man's perfect vacation? Skyscraper with room service and 5G! 🏢📶",
"📜 Spider-Man's real motto: 'Great power, great responsibility, greater naps!' 💤⚡",
"🎙️ Why did Spider-Man podcast? 'Web-Slinging 101: A Masterclass' 🕸️🎧"
];

const UPLOAD_JOKES = [
"⏰ This upload is taking longer than Garfield realizing he's hungry (0.002 seconds) 🍝😹",
"💪 I'm working harder than Jon on his 'diet' (lasted exactly one salad) 🥗➡️🍕",
"🎨 Uploading files is like watching paint dry... except paint has personality! 😴🖌️",
"🍝 If this upload were lasagna, it'd be the burnt kind Jon makes when he's trying to impress dates! 🔥😬",
"⏳ This process is so slow I could've made lasagna, eaten it, napped, and made another lasagna! 🍝😴🍝",
"🐕 I'm being more productive than Odie after his third espresso! ☕☕☕ (He's vibrating)",
"💤 Uploading files: where even Garfield would lose patience (impossible but here we are) 😾⏰",
"🍝 This is taking longer than Jon realizing he needs therapy for talking to his cat! 🧠💭",
"📰 This is harder than getting Odie to fetch the newspaper without eating the sports section! 🐕📄",
"🐱 I'm working harder than a cat trying to open a tuna can with pure determination! 🥫💪",
"😴 This upload is taking longer than my legendary 16-hour power nap! 💤⏰",
"🍝 I'd rather be inhaling lasagna, but someone has to adult around here! 😤👔",
"😹 This is more exhausting than dodging Nermal's aggressive cuteness! 🐱✨",
"📅 Working on a Monday? This violates the Geneva Convention! 😤⚖️",
"💑 I'm putting more effort into this than Jon's entire dating career! 💔📊",
"🐕 This is almost as satisfying as yeeting Odie off the table! Almost. 🦵💥",
"🍝 If uploads were lasagna, I'd have diabetes by now! 🎂📈",
"🏆 I'm being more productive than Jon has been since 1978! 📅✨",
"🐌 This upload is moving slower than Garfield on a treadmill (stationary) 🏃‍♂️❌",
"🍌 Uploading files is like waiting for minions to speak English - theoretically possible, practically BANANA! 🗣️🍌",
"💇‍♂️ This is taking longer than Andrew Garfield's hair care routine! 💆‍♂️✨",
"🕸️ I've seen Spider-Man cross NYC faster than this uploads one megabyte! 🏙️💨",
"📅 This upload speed makes Garfield's Monday motivation look like The Flash! ⚡🐌",
"🍌 Even a minion with a broken banana would upload faster! 🍌🔧",
"🚗 This is more painful than watching Jon parallel park (17 attempts minimum) 🅿️😬",
"🐢 Upload progress: Moving at the speed of Garfield chasing vegetables! 🥦🚫",
"🐕 This file uploads like Odie delivers mail - maximum chaos, zero progress! 📬💥",
"🗣️ I could teach a minion Shakespeare faster than this uploads! 🍌📚 'To banana or not to banana!'"
];

const CONVERSION_JOKES = [
"🎵🎉 MP3s detected! I can merge them faster than Odie loses at chess (instantly)! Should we make audio magic? ✨🎧",
"🎵🐕 These files are scattered like Odie's brain cells during a thunderstorm! Let me organize them into one beautiful M4B! 🧠⚡",
"🎵😴 MP3 conversion time! Almost as exciting as Garfield finding lasagna... in his dreams! 🍝💭",
"🎵☕ Found your MP3 files! I'll combine them while you grab coffee (or take a Garfield-level nap)! 😴💤",
"🎵🍝 These MP3s need merging like lasagna layers need cheese - desperately and with love! 🧀❤️",
"🎵📅 This audiobook has more MP3s than Garfield has complaints about existence! Converting to M4B will take longer than his post-lasagna coma! Ready? 😴🍝",
"🎵✨ Found MP3 files! Converting to M4B is like making the perfect lasagna - time-consuming but SO worth it! Should I commence the audio alchemy? 🧙‍♂️🎭",
"🎵🧠 These MP3 files are scattered like Odie's thoughts (what thoughts?)! I'll organize them into a beautiful M4B! Perfect nap-time activity! 💤📚",
"🎵💑 MP3 conversion! More exciting than Jon's dating life (low bar but still)! Convert anyway? 😬💘",
"🎵🤝 Converting these MP3s is like getting Andrew Garfield and Garfield to share a pizza - complicated but achievable! Ready for magic? 🍕✨",
"🎵🕸️ I'll merge these files faster than Spider-Man can say his whole catchphrase! (Okay maybe not THAT fast) Continue? 🕷️💨",
"🎵🍌 These MP3s are more scattered than minions at a 50% off banana sale! Let me web them into one glorious M4B! Sound good? 🕸️🍌",
"🎵📅 Converting MP3s to M4B: Like teaching Garfield to love Mondays - technically possible with enough patience! Shall we? 😤⏳",
"🎵💇‍♂️ I can combine these files like Andrew Garfield combines acting talent with perfect hair physics! Ready for audio excellence? ✨🎬",
"🎵💤 These files need merging like Garfield needs his 23-hour beauty sleep - DESPERATELY! Let me help! Convert? 😴💅",
"🎵🎉 MP3 to M4B conversion: Less chaotic than a minion birthday party, more organized than Odie's sock drawer! Begin? 🧦🍌",
"🎵🍌 I'll merge these files with the enthusiasm of a minion finding the banana motherload! Start the conversion party? 🎊🍌",
"🎵🍝 Converting these is easier than explaining to Garfield why we can't have lasagna for breakfast, lunch, AND dinner! Ready? 🍳🍝🍽️",
"🎵💥 These MP3s are about to become one M4B, like how all of Jon's dating disasters become one therapy session! Convert? 💔➡️🧠"
];

// Combined generic jokes collection
const allJokes = [
  ...garfieldJokes,
  ...minionJokes,
  ...spiderManJokes
];

export function getPersonality(topic?: string): string {
  // If a topic is provided, we could filter jokes based on the topic
  // For now, we'll just return a random joke regardless of topic
  // (but we're acknowledging the parameter to avoid TypeScript warnings)
  if (topic) {
    // In the future we could filter jokes by topic
    // For now we just acknowledge the parameter
  }
  const randomIndex = Math.floor(Math.random() * allJokes.length);
  return allJokes[randomIndex];
}

export function getRandomUploadJoke(): string {
  const uploadJokes = [...UPLOAD_JOKES, ...garfieldJokes];
  return uploadJokes[Math.floor(Math.random() * uploadJokes.length)];
}

export function getRandomConversionJoke(): string {
  return CONVERSION_JOKES[Math.floor(Math.random() * CONVERSION_JOKES.length)];
}