const garfieldJokes = [
  "I'm so sarcastic, I make Garfield look like a motivational speaker.",
  "I'd rather be napping than doing this work. Just like Garfield would rather nap than eat... but that's not possible.",
  "This is more frustrating than trying to explain to Odie why he can't have lasagna!",
  "I'm working harder than Garfield when he's pretending to be asleep so Jon won't make him go outside.",
  "If I were a cat, my life would consist of sleeping, eating, and complaining about Mondays. Just like Garfield.",
  "I've got more energy than Garfield in the morning... Wait, no. That's impossible.",
  "This feels like trying to get Garfield interested in something other than food.",
  "I'm working harder than Garfield when he's pretending to be hungry but actually just wants attention.",
  "Garfield's life philosophy: Eat lasagna, sleep, complain about Mondays, repeat. My work philosophy? Try not to nap at my desk.",
  "Why did Garfield refuse to play cards? Too many cheetahs!",
  "What does Garfield say when he falls asleep in a meeting? 'I'm just resting my eyes... for the next eight hours.'",
  "Why did Garfield fail his driving test? He couldn't stop hitting the snooze button.",
  "How does Garfield organize his books? By how tired they make him feel.",
  "What's Garfield's favorite exercise? The couch to bed sprint.",
  "Why did Garfield become a photographer? To capture perfect naps in natural light.",
  "What's Garfield's idea of a party? A quiet room with lots of pillows and zero people.",
  "How does Garfield flirt? By looking adorable while pretending not to care.",
  "What's Garfield's favorite app? Sleepify.",
  "Why did Garfield get a degree in philosophy? To justify his naps for the rest of his life.",
  "Why did Garfield sit on the computer? He wanted to keep an eye on the mouse!",
  "What's Garfield's favorite dance? The lasagna shuffle!",
  "Why did Garfield eat the clock? He wanted seconds!",
  "What's Garfield's favorite sport? Couch surfing!",
  "Why did Garfield bring a ladder to the kitchen? To reach the top layer of lasagna!",
  "Why did Garfield hate Mondays? Too much cat-itude!",
  "What does Garfield put in his smoothies? Paw-sicles!",
  "Why did Garfield become a chef? For the purr-fect lasagna!",
  "What does Garfield say to Jon? 'More lasagna or else!'",
  "What's Garfield's favorite cryptocurrency? Napkin.",
  "Why did Garfield start a podcast? So he could record it lying down.",
  "What's Garfield's workout routine? 12 reps of hitting snooze.",
  "How does Garfield meditate? He doesn't - sleeping is his meditation.",
  "What's Garfield's favorite movie genre? Anything under 90 minutes so he can nap sooner.",
  "Why did Garfield join LinkedIn? To network horizontally.",
  "What's Garfield's favorite social media? Insta-nap.",
  "How does Garfield handle stress? By delegating it to Odie.",
  "What's Garfield's favorite type of meeting? The cancelled kind.",
  "Why did Garfield become a life coach? To teach the art of strategic laziness.",
  "Garfield's secret weapon: Napping before deadlines. It works better than coffee.",
  "Why is Garfield so good at procrastination? He's got more time than Jon has patience.",
  "What do you call Garfield's nap routine? Sleep-ology, because it's a science.",
  "Garfield's advice for lazy days: 'I'll nap after I eat my lasagna.'",
  "Why does Garfield prefer to sleep on the couch? Because it's easier than climbing up the stairs."
];

const minionJokes = [
  "I'm working harder than a minion trying to make sense of human instructions.",
  "This is more frustrating than explaining calculus to a group of minions!",
  "I've got more energy than a minion after a double espresso banana smoothie!",
  "If I were a minion, my resume would say 'Professional chaos maker and banana enthusiast'.",
  "Minions think they're being productive by dancing around. I actually have to do real work.",
  "This feels like trying to herd cats... made of bananas.",
  "I'm working harder than a minion who just discovered Wi-Fi!",
  "Minion philosophy: Work is optional, bananas are mandatory. My philosophy? Coffee is life.",
  "I'm more enthusiastic about my lunch break than a minion about party time!",
  "Why did the minion bring a ladder to the banana stand? To reach new heights of silliness!",
  "What's a minion's favorite weather? Banana-y sunshine!",
  "Why did the minion wear sunglasses inside? Because he was 'banana-cular'!",
  "How do you organize a space party with minions? You planet!",
  "What do you call a minion magician? A banan-a-biz!",
  "Why did the minion break up with his girlfriend? She couldn't handle his banana-ness.",
  "What's a minion's favorite type of story? A banana-tale!",
  "How does a minion say goodbye? 'See you later, alligator!' (But really, he'll be back for bananas.)",
  "Why did the minion get a job at the zoo? To hang out with his fellow primates... and eat more bananas.",
  "What's a minion's favorite exercise? The banana-split!",
  "Why was the minion so good at hide and seek? Because he could turn invisible when near bananas.",
  "How does a minion count to ten? One banana, two banana, three banana...",
  "What's a minion's favorite board game? Bananagram!",
  "Why did the minion fail his driving test? He kept turning into a banana peel at corners.",
  "What's a minion's favorite holiday? Banana-kin Day!",
  "How does a minion apologize? 'I'm bananas about you' (and then hands over a banana).",
  "Why did the minion become an artist? To draw more bananas!",
  "What's a minion's dream job? Professional banana taster.",
  "Why was the minion so good at karate? He had perfect balance thanks to all those bananas.",
  "Why did the minion bring a banana to bed? For a midnight snack!",
  "What do minions use to write letters? Banana pens!",
  "Why did the minion cross the road? To get to the banana store!",
  "What's a minion's favorite instrument? The bananjo!",
  "Why did the minion wear glasses? To improve his banana vision!",
  "What's a minion's favorite movie? The Banana Identity!",
  "Why did the minion bring a suitcase? For banana vacations!",
  "What's a minion's favorite game? Hide and banana seek!",
  "Why did the minion sit on the clock? He wanted to banana split!",
  "What's a minion's favorite song? Banana-nanana (Batman theme)!",
  "What's a minion's favorite programming language? Python... because it sounds like a banana variety.",
  "Why did the minion become a DJ? To drop the banana beats!",
  "What's a minion's favorite Shakespeare play? Much Ado About Bananas.",
  "How does a minion solve problems? By throwing bananas at them until something works.",
  "What's a minion's favorite conspiracy theory? The moon is made of frozen bananas.",
  "Why did the minion become a therapist? To help others peel back their layers.",
  "What's a minion's favorite pickup line? 'Are you a banana? Because I find you a-peel-ing!'",
  "How does a minion celebrate New Year's? By making banana resolutions they'll break by January 2nd.",
  "What's a minion's favorite type of comedy? Slap-stick... with banana peels.",
  "Why did the minion become a meteorologist? To predict banana rain.",
  "Minion's secret talent: Making coffee that tastes like banana smoothies. It's a real skill.",
  "Why don't minions ever get lost in the forest? Because they always follow the banana trail!",
  "What do you call a minion with a PhD? A banana-ologist!",
  "Why did the minion start a business? To sell banana-themed products... and nap.",
  "Minion's favorite quote: 'I'm bananas about bananas!'"
];

const spiderManJokes = [
  "This is more frustrating than trying to get Spider-Man to take a break from saving the world!",
  "I'm working harder than Spider-Man when he's on patrol.",
  "I've got more energy than Spider-Man after a good nap!",
  "I'm more focused than Spider-Man when he's watching his own movie. Well, that's not saying much.",
  "If I were a spider, I'd be spinning webs like Spider-Man! ...But I'm not a spider, so I'll just work.",
  "This feels like a mission impossible for Spider-Man! But I've got more determination than Spider-Man when he's trying to save the city.",
  "Spider-Man's philosophy: With great power comes great responsibility. My philosophy: With great work comes great productivity.",
  "I'm working harder than Spider-Man when he's fighting crime!",
  "I'm more determined than Spider-Man when he's on a mission.",
  "Why did Spider-Man bring a net to the party? To catch some web-slingers!",
  "What's Spider-Man's favorite dessert? Pie à la mode (while hanging upside down)!",
  "Why did Spider-Man hate math? Too many arachnid equations!",
  "What's Spider-Man's favorite ride? The Ferris wheel (good web anchor)!",
  "Why did Spider-Man go to art school? To improve his web designs!",
  "What does Spider-Man put on pancakes? Maple sy-web!",
  "Why did Spider-Man visit the bank? To check his web interest!",
  "What's Spider-Man's favorite exercise? Wall sits!",
  "Why did Spider-Man become a chef? For perfect spider-rolls!",
  "What's Spider-Man's favorite music? Rock and roll (for climbing walls)!",
  "Andrew Garfield as Spider-Man is amazing, but I bet even he can't climb walls after eating Garfield's lasagna.",
  "If Andrew Garfield and Garfield had a staring contest, who would win? Garfield - because he'd close his eyes first.",
  "What do you call it when Andrew Garfield and Garfield team up? Spidey vs. the Monday blues.",
  "Why did Andrew Garfield invite Garfield to his party? Because every good party needs a professional napper.",
  "If Garfield were a superhero, what would his power be? The ability to sleep through anything.",
  "What's the difference between Andrew Garfield and Garfield? One swings from buildings, the other swings from couch cushions.",
  "Why did Garfield refuse to watch 'The Amazing Spider-Man'? Too many action scenes interrupted his nap.",
  "If Garfield had spider powers, he'd probably use them to steal more lasagna.",
  "What's Garfield's favorite superhero movie? 'Nap Man Begins'.",
  "How does Garfield react when Andrew Garfield swings by? He yawns and goes back to sleep.",
  "Why was Andrew Garfield's Spider-Man so good at skateboarding? He had amazing balance.",
  "What's Andrew Garfield's Spider-Man's favorite subject? Web design, with a minor in angst.",
  "How does Andrew Garfield's Spider-Man take his photos? With a web-cam.",
  "Why did Andrew Garfield's Spider-Man get a job at Oscorp? For the great web-nefits.",
  "What did Gwen Stacy say to Andrew Garfield's Spider-Man? 'You're amazing!'",
  "Why was Andrew Garfield's Spider-Man so quippy? He had a great sense of spider-timing.",
  "What's Andrew Garfield's Spider-Man's favorite band? The Web-Strokes.",
  "Why did they call it 'The Amazing Spider-Man'? Because 'The Pretty Good Spider-Man' didn't have the same ring to it.",
  "How did Andrew Garfield's Spider-Man fix his suit? With a spider-patch.",
  "What's Andrew Garfield's Spider-Man's favorite drink? A web-presso.",
  "Why was Andrew Garfield's Spider-Man always on his phone? He was checking his web-slinger account.",
  "What does Andrew Garfield's Spider-Man do in his free time? Surfs the world wide web.",
  "Why did Andrew Garfield's Spider-Man break up with his girlfriend? It was a sticky situation.",
  "What's Andrew Garfield's Spider-Man's favorite type of story? A spin-off.",
  "Why is Andrew Garfield's Spider-Man so good at science? He's got a knack for it.",
  "What car does Andrew Garfield's Spider-Man drive? A convertible, for easy web-slinging.",
  "Why did Andrew Garfield's Spider-Man join the science club? To meet new lab partners.",
  "What's Andrew Garfield's Spider-Man's biggest fear? A web browser crash.",
  "Why did Andrew Garfield's Spider-Man get a library card? To check out books on arachnids.",
  "What's Andrew Garfield's Spider-Man's favorite hobby? Hanging out.",
  "Why did Andrew Garfield's Spider-Man get detention? For climbing the walls.",
  "What's Andrew Garfield's Spider-Man's favorite movie genre? Web-sterns.",
  "Why did Andrew Garfield's Spider-Man go to the park? To swing.",
  "What's Andrew Garfield's Spider-Man's favorite part of a joke? The punch-line.",
  "Why was Andrew Garfield's Spider-Man a good photographer? He always got the right angle.",
  "What's Andrew Garfield's Spider-Man's favorite food? Anything that sticks to the wall.",
  "Why did Andrew Garfield's Spider-Man get a new suit? His old one was too web-worn.",
  "What's Andrew Garfield's Spider-Man's favorite day of the week? Web-nesday.",
  "Why did Andrew Garfield's Spider-Man go to the top of the Empire State Building? For the view and the Wi-Fi.",
  "What's Andrew Garfield's Spider-Man's life motto? 'Just wing it.'",
  "Why did Andrew Garfield's Spider-Man get a skateboard? It was faster than crawling in traffic.",
  "What's Andrew Garfield's Spider-Man's favorite type of math? Web-calculus.",
  "Why did Andrew Garfield's Spider-Man like chemistry? Because of the bonds.",
  "What's Andrew Garfield's Spider-Man's favorite accessory? A web-belt.",
  "Why did Andrew Garfield's Spider-Man get a good grade in physics? He understood the laws of motion.",
  "What's Andrew Garfield's Spider-Man's favorite place to visit? The web-site of the Grand Canyon.",
  "Why did Andrew Garfield's Spider-Man get a part-time job? To pay for his web-hosting.",
  "What's Andrew Garfield's Spider-Man's favorite kind of joke? A real knee-slapper... or wall-crawler.",
  "Why did Andrew Garfield's Spider-Man like his high school? It had a great science department.",
  "What's Andrew Garfield's Spider-Man's favorite thing about New York? The tall buildings.",

  "What happens when Andrew Garfield plays Garfield in a movie? The most confusing credits ever.",
  "If Andrew Garfield voiced Garfield, would it be called 'The Amazing Lazy Cat'?",
  "Andrew Garfield's workout routine: Swing from buildings. Garfield's workout routine: Swing from the chandelier to steal cookies.",
  "What's the difference between Andrew Garfield's diet and Garfield's diet? One involves protein shakes, the other involves entire lasagnas.",
  "If Andrew Garfield and Garfield switched lives for a day, who would be more upset? Jon, definitely Jon.",
  "Why doesn't Andrew Garfield have a cat named Garfield? Too confusing at the vet.",
  "What would happen if Garfield got bit by a radioactive spider? He'd use his powers to web lasagna directly to his mouth.",
  "Andrew Garfield fights villains. Garfield fights alarm clocks. Both are heroes in their own way.",
  "If there was a Garfield multiverse, would Andrew Garfield be in it? Only if there's lasagna.",
  "What's Andrew Garfield's favorite day? Not Monday - he shares that with the other Garfield.",
  "Spider-Man's secret talent: Making web-slinging look effortless. Even when he's just napping.",
  "Why did Spider-Man get a pet spider? Because it was too busy to be his own superhero.",
  "What's Spider-Man's favorite vacation spot? The top of a skyscraper with a great view and Wi-Fi.",
  "Spider-Man's motto: 'With great power comes great responsibility... and great naps.'",
  "Why did Spider-Man start a podcast? To share his web-slinging tips with the world."
];

const UPLOAD_JOKES = [
  "This upload is taking longer than it takes Garfield to realize he's hungry again.",
  "I'm working harder than Jon does on his 'diet' (which lasts about as long as Odie's attention span).",
  "Uploading files is like watching paint dry... except less interesting and with more potential for failure.",
  "If this upload were a lasagna, it would be the kind that burns because you forgot about it in the oven.",
  "This process is so slow I could have baked a lasagna, eaten it, taken a nap, and still not finished uploading.",
  "I'm being more productive than Odie after his second bowl of kibble. And by 'productive', I mean I've managed to stay awake.",
  "Uploading files: where even Garfield would lose patience (and then go take a nap).",
  "This is taking longer than it takes Jon to realize he's out of lasagna and needs to make more.",
  "This is harder than getting Odie to fetch the newspaper without eating it first.",
  "I'm working harder than a cat trying to open a can of tuna with no thumbs.",
  "This upload is taking longer than my afternoon nap. And that's saying something!",
  "I'd rather be eating lasagna, but someone has to do the work around here.",
  "This is more exhausting than dodging Nermal's attempts at being cute.",
  "Working on a Monday? This goes against everything I believe in.",
  "I'm putting more effort into this than Jon puts into his dating life.",
  "This is almost as satisfying as pushing Odie off the table. Almost.",
  "If uploads were lasagna, this would be a feast!",
  "I'm being more productive than Jon on his best day.",
  "This upload is moving slower than Garfield on a treadmill.",
  "Uploading files is like waiting for a minion to stop saying 'banana' - theoretically possible, practically never happening.",
  "This is taking longer than Andrew Garfield's hair routine before filming.",
  "I've seen Spider-Man swing across New York faster than this file uploads.",
  "This upload speed makes Garfield's Monday motivation look lightning fast.",
  "Even a minion with a broken banana wouldn't be this slow.",
  "This is more painful than watching Jon try to parallel park.",
  "Upload progress: Moving at the speed of Garfield chasing vegetables.",
  "This file is uploading like it's being carried by Odie - lots of enthusiasm, zero speed.",
  "I could train a minion to speak proper English faster than this uploads."
];

const CONVERSION_JOKES = [
  "🎵 MP3s detected! I can merge them into an M4B file faster than Odie can figure out that the red dot isn't real. Should we begin?",
  "🎵 These files are scattered like Odie's toys after a playful evening. Let me organize them into one nice M4B - it'll be like magic... but slower.",
  "🎵 MP3 conversion time! This is almost as exciting as when Garfield finds an empty lasagna pan. Almost.",
  "🎵 Found your MP3 files! I can combine them into a single M4B while you take a coffee break (or a nap, if you're more like Garfield).",
  "🎵 These MP3s need to be one M4B file. Think of it as combining all the layers of a lasagna - messy at first, but delicious in the end.",
  "🎵 This audiobook has more MP3s than I have complaints about Mondays. We can convert them to a single M4B file, but it'll take longer than my post-lasagna nap. What do you say?",
  "🎵 Found MP3 files! Converting them to M4B is like combining all the layers of a lasagna into one perfect bite. It takes time, but it's worth it. Should I do the magic?",
  "🎵 These MP3 files are scattered like Odie's brain cells. I can organize them into a nice M4B file. It'll take a while - perfect time for a nap. Shall I proceed?",
  "🎵 MP3 conversion time! This is more exciting than watching Jon try to impress a date. And by exciting, I mean I'd rather be sleeping. Convert anyway?",
  "🎵 Converting these MP3s is like getting Andrew Garfield and Garfield to agree on something - complicated but doable. Ready?",
  "🎵 I'll merge these files faster than Spider-Man can say 'with great power comes great responsibility'. Well, maybe not THAT fast. Continue?",
  "🎵 These MP3s are more scattered than minions at a banana sale. Let me web them together into one M4B. Sound good?",
  "🎵 Converting MP3s to M4B: It's like teaching Garfield to love Mondays - technically possible but requires patience. Shall we?",
  "🎵 I can combine these files like Andrew Garfield combines acting talent with perfect hair. Ready to make some audio magic?",
  "🎵 These files need merging like Garfield needs his beauty sleep - desperately. Let me help with that. Convert?",
  "🎵 MP3 to M4B conversion: Less chaotic than a minion birthday party, more organized than Odie's thoughts. Begin?",
  "🎵 I'll merge these files with the enthusiasm of a minion finding a banana plantation. Start the conversion?",
  "🎵 Converting these is easier than explaining to Garfield why we can't have lasagna for every meal. Ready to proceed?",
  "🎵 These MP3s are about to become one M4B, like how all of Jon's dating disasters become one big life lesson. Convert?"
];

// Combined jokes collection
const allJokes = [
  ...garfieldJokes,
  ...minionJokes,
  ...spiderManJokes
];

export function getPersonality(): string {
  const randomIndex = Math.floor(Math.random() * allJokes.length);
  return allJokes[randomIndex];
}

export function getRandomUploadJoke(): string {
  const uploadJokes = [...UPLOAD_JOKES, ...garfieldJokes];
  return uploadJokes[Math.floor(Math.random() * uploadJokes.length)];
}

export function getRandomConversionJoke(): string {
  return CONVERSION_JOKES[Math.floor(Math.random() * CONVERSION_JOKES.length)];
}
